version: "3.3"
services:
  mongo:
    image: mongo
    hostname: "mongo"
    environment:
      - MONGO_INITDB_DATABASE=logs # todo: research external parameters

    ports:
      - "27017-27019:27017-27019"
    # TODO: research usage of volumes for persistance
  logger-service:
    build: .\lite_logger
    ports:
      - target: 3000
        published: 3000
    depends_on:
      - mongo
    environment:
      - MONGO_HOST=mongo
  logger-application:
    build: .\Logger-lite-application
    ports: 
      - target: 3001
        published: 3001
    depends_on: 
      - logger-service
    environment: 
      - PORT=3001
      - BACKEND_ADDRESS=logger-service
      - BACKEND_PORT=3000